import sys
import subprocess

# --- DEPENDENCY BOOTSTRAPPER ---
def ensure_deps():
    deps = {'termcolor': 'termcolor'}
    for pkg, module in deps.items():
        try:
            __import__(module)
        except ImportError:
            print(f"[*] Missing '{pkg}'. Auto-installing...")
            subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])
ensure_deps()
# -------------------------------

import csv
import re
import os
from termcolor import colored

def parse_threat_intel(csv_file_path, content_column_index=3):
    print(colored(f"--- INITIATING AUTOMATED THREAT INTEL PARSER ---", "blue", attrs=["bold"]))
    print(f"[*] Ingesting Target Archive: {csv_file_path}")
    
    if not os.path.exists(csv_file_path):
        print(colored("[-] Critical Error: CSV Archive not found.", "red"))
        return

    # Compile Regular Expressions for high-speed parsing
    patterns = {
        "BTC_Wallets": re.compile(r'\b(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,39}\b'),
        "Monero_Wallets": re.compile(r'\b4[0-9AB][1-9A-HJ-NP-Za-km-z]{93}\b'),
        "IPv4_Nodes": re.compile(r'\b(?:\d{1,3}\.){3}\d{1,3}\b'),
        "Tor_Onion_Links": re.compile(r'\b[a-z2-7]{16,56}\.onion\b'),
        "Mega_Links": re.compile(r'https?://mega\.nz/(?:file|folder)/[a-zA-Z0-9#_-]+')
    }
    
    # Sets automatically prevent duplicate entries
    extracted_iocs = {key: set() for key in patterns.keys()}
    messages_scanned = 0
    
    print(colored("[*] Executing deep Regex scan across raw text payload...", "yellow"))
    
    try:
        with open(csv_file_path, mode='r', encoding='utf-8') as f:
            reader = csv.reader(f)
            next(reader, None) # Skip the header row
            
            for row in reader:
                if len(row) > content_column_index:
                    message_text = row[content_column_index]
                    messages_scanned += 1
                    
                    # Scan message against all patterns
                    for ioc_type, pattern in patterns.items():
                        matches = pattern.findall(message_text)
                        for match in matches:
                            # Handle tuples returned by some complex regex groups
                            if isinstance(match, tuple):
                                match = match[0]
                            extracted_iocs[ioc_type].add(match)

        print(colored(f"[✓] Scan Complete. Processed {messages_scanned} individual messages.", "green"))
        
        # Output the intelligence
        report_file = "Extracted_IOC_Report.txt"
        with open(report_file, "w") as out:
            out.write("=========================================\n")
            out.write(" AUTOMATED THREAT INTELLIGENCE REPORT\n")
            out.write("=========================================\n\n")
            
            for ioc_type, iocs in extracted_iocs.items():
                header = f"--- {ioc_type.replace('_', ' ').upper()} FOUND: {len(iocs)} ---"
                out.write(f"{header}\n")
                print(colored(f"\n{header}", "cyan", attrs=["bold"]))
                
                for ioc in iocs:
                    out.write(f"{ioc}\n")
                    print(f" [+] {ioc}")
                out.write("\n")
                
        print(colored(f"\n[*] Actionable intelligence secured to: {report_file}", "blue", attrs=["bold"]))

    except Exception as e:
        print(colored(f"[-] Parsing Error: {e}", "red"))

if __name__ == "__main__":
    # Example Usage: Point to the CSV generated by the Telegram or Discord archiver
    # Ensure the content_column_index matches where the text actually is in your CSV
    parse_threat_intel("Discord_Archive_123456789012345678.csv", content_column_index=3)